version: "3"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "./mysql:/var/lib/mysql"

  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1